# Labels.
"type:feature": [ 'feature/*', 'feat/*' ]
"type:bug": [ 'bug/*', 'bugfix/*', 'fix/*' ]
"type:hotfix": [ 'hotfix/*', 'hot/*' ]
"type:docs": [ 'docs/*', 'doc/*' ]
"type:enhancement": [ 'enhancement/*', 'enhance/*', 'chore/*' ]
"type:maintenance": [ 'maintenance/*', 'robot/*', 'devops/*', 'update/*' ]
"type:dependency": [ 'renovate/*', 'update/*', 'deps/*' ]
