# Code Climate configuration
# ~~
# This file is used only for local validations over Code Climate CLI.
# See more: https://github.com/codeclimate/codeclimate
version: "2"         # required to adjust maintainability checks
plugins:
  scalastyle:
    enabled: false
  checkstyle:
    enabled: false
    channel: "beta"
    config:
      file: "conf/checkstyle/checkstyle-config.xml"
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "11"
      tests_patterns:
        - test/**
  pmd:
    enabled: true
    config:
      rules:
        - "java-basic"
  markdownlint:
    enabled: true