# Continouos Integration action.
# ~~~~
name: "CI"
on:
  release:
    types: [ created ]
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, '**' ]
  schedule:
    - cron: '45 3 * * 1'

jobs:
  validate:
    name: Validate Code
    if: "(github.event.release || github.event.release.prerelease) == false"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '11'
          cache: 'sbt'

      - name: Check Project Code
        run: sbt validateCode

      - name: Upload ScalaStyle Report (XML)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: scalastyle-reports
          path: ${{github.workspace}}/target/scalastyle-report/

  build:
    name: Build & Analyze
    if: "(github.event.release || github.event.release.prerelease) == false"
    continue-on-error: ${{ matrix.experimental }}
    needs: [ validate ]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        distribution: [ 'corretto' ]
        jdk: [ '11' ]
        scala: [ '2.13.8' ]
        experimental: [ false ]
        include:
          - jdk: '17'
            distribution: 'corretto'
            scala: '2.13.8'
            experimental: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
          cache: 'sbt'

      - name: Perform Build / Test
        run: sbt ++${{ matrix.scala }} compile test

  publish:
    name: Publish to Sonatype
    if: "github.event.release || github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
          cache: 'sbt'

      - name: Publish package
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
