name: "CI"
on:
  release:
    types: [ created ]
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, '**' ]
  schedule:
    - cron: '45 3 * * 1'
jobs:
  lint:
    name: Verify ScalaFmt
    if: "(github.event.release || github.event.release.prerelease) == false"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '11'
          cache: 'sbt'

      - name: Set GitHub token
        run: git config --global github.token $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check ScalaFmt
        run: sbt scalafmtSbtCheck scalafmtCheck Test/scalafmtCheck

  checkstyle:
    name: Verify Checkstyle / ScalaStyle
    if: "(github.event.release || github.event.release.prerelease) == false"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: '11'
          cache: 'sbt'

      - name: Set GitHub token
        run: git config --global github.token $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check ScalaFmt
        run: sbt checkstyle Test/checkstyle

      - name: Check ScalaStyle
        run: sbt scalastyle test:scalastyle

      - name: Upload Checkstyle (XML)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: java-checkstyle-reports
          path: ${{github.workspace}}/target/checkstyle-report.xml

      - name: Upload Style Report (XML)
        uses: actions/upload-artifact@v3.1.0
        with:
          name: scalastyle-reports
          path: ${{github.workspace}}/target/scalastyle-report/

  build:
    name: Build & Analyze
    if: "(github.event.release || github.event.release.prerelease) == false"
    continue-on-error: ${{ matrix.experimental }}
    needs: [ lint, checkstyle ]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        distribution: [ 'corretto' ]
        jdk: [ '11' ]
        scala: [ '2.13.8' ]
        experimental: [false]
        include:
          - jdk: '17'
            distribution: 'corretto'
            scala: '2.13.8'
            experimental: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
          cache: 'sbt'

      - name: Set GitHub token
        run: git config --global github.token $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Perform Build / Test
        run: sbt ++${{ matrix.scala }} compile test

  publish:
    name: Publish to GH Packages
    if: "github.event.release || github.event.release.prerelease"
    runs-on: ubuntu-latest
    needs: [ build ]

    strategy:
      fail-fast: true
      matrix:
        distribution: [ 'corretto' ]
        jdk: [ '11' ]
        scala: [ '2.13.8' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.jdk }}
          cache: 'sbt'

      - name: Set GitHub token
        run: git config --global github.token $TOKEN
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        run: sbt ${{ matrix.scala }} publish
